export const coffees = [
  {
    id: 1,
    tags: ['tradicional'],
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaW6h5K4j3I3FrDVNpUxQYE4b5OOIM-T3Q-fgHvWhKhXNUrfSn7iKIXuNKou52yDXdtfZHO_NG3PcOFGlRyYiiwIpJYZ1wFum9uOMLd0AiP6rxqVymBtrZ4jO6RyM4UiUIWV2yqci42qsaT8k6TlnxbP=w120-h120-s-no?authuser=0',
    price: "8,90",
  },
  {
    id: 2,
    tags: ['tradicional'],
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaW5v1vT3VhrpaygB1OiXSb20iMhwnS22Z1birGLlHwbwNoNB3tr2IFx1tZlUFwIeJysbEbINGqmMvqcxIcP9hx51zuBgJtzuQF9RQLvBl1XCNpIltj7spbm_RiVASnsU-da6nyb6ng5MYHS4wqC-Y7N=w120-h120-s-no?authuser=0',
    price: "9,90",
  },
  {
    id: 3,
    tags: ['tradicional'],
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaU6a9344b_6PMc9VJ9xJpyv7H33ohCE46iyNoeQS23X1IsZ-iQr4G9jVuJrS60SwVlf4mAxnuDfbVlEX0H-d4k0bICBRrw2qzlxVRJ1KpoL2Mc4_2n1DAEytCN79XRZSibSgonmdE9EoSwH8dtKZ6Io=w120-h120-s-no?authuser=0',
    price: "9,90",
  },
  {
    id: 4,
    tags: ['tradicional', 'gelado'],
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaVme-YJ-SOw0gkaO0qROcgd8PcaLeTMKpYmnlnAMLVYyKRhirdJ6mdQMC2QotOm1_udlWVkbBMeRfP8gQPIG-y5rxoZ_-O0-THSDXcEEr4djzGdJ26MUwyD9e27y98eOi5sX1FGiVsyBR29oAwZJD3H=w120-h120-s-no?authuser=0',
    price: "9,90",
  },
  {
    id: 5,
    tags: ['tradicional', 'com leite'],
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaWY4mcWobDM2VM-Xo0mq6P08j_tCM34_3BcWkOIAM9Z3kwpmyhbKm07hf9bSth2H4AW4ckKzlzmzuKO-2JMOdMMunYoDnqNofbkxMEvQUwXb_MQpbjZfLzZ0JEKnkt59tGVHdwd-E1lYT2w7GSCAcW7=w120-h120-s-no?authuser=0',
    price: "8,50",
  },
  {
    id: 6,
    tags: ['tradicional', 'com leite'],
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaXPNvGxYvKPARGE6uc-4ySQth3l7rQn4B8w1HG0l-omqzVxwm1VPvbZsMAQxuhR9MgG5Zc8kIra3cBeN95zQYPsvDly9N5TS7mS2CyYQxgni_1xgDGrTzhnjTWlztpi4HFCDUabkFo3FISQ1F9IkQVh=w120-h120-s-no?authuser=0',
    price: "19,90",
  },
  {
    id: 7,
    tags: ['tradicional', 'com leite'],
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaX1oMo4kUD9qgkvJsWWsrR2BpkwUEAmQhiJYjga-T8Y1QorigHOGcd1fWsYbNAnFcJD4Y4Xkv_alQax91mc-yrKUC3mVIgnggT6G97U_H4yn7DYBN9Wcp9lTgv-KxIN4zr9krnwo4wFmboAcdllYKsg=w120-h120-s-no?authuser=0',
    price: "12,00",
  },
  {
    id: 8,
    tags: ['tradicional', 'com leite'],
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaVJ0kUcR3qeKAEMTEwlPb_GxYy1qumxy2yapRf1E4ibvk_zIeJBJdxcifTMZ4RuV_PisSnGzjiXmRCz8fLLi_r-c1jU673EJGrLb1_EadCZAvmtV4SW4gw9MFVixiDkNu5ONXwQ-vZ8dPtGWYfFQZMB=w120-h120-s-no?authuser=0',
    price: "9,90",
  },
  {
    id: 9,
    tags: ['tradicional', 'com leite'],
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaVMO-LSPUk0P92XEKo0x-zNq2XyjBaE5uJaOhr9PX3kiB4nJGCqg7cSZ9yVg9jnL5NtWL8EiIkueV9hhLZwG0mAjVrqKMeg0WbTZ9b93BUZx3tcqJrvcq5S9RUa_U_NBZvARgbSR1M4o5tms6TM81h-=w120-h120-s-no?authuser=0',
    price: "19,90",
  },
  {
    id: 10,
    tags: ['especial', 'com leite'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaXmV4zx4h6PYUWFZeFDr2uq2udvoUgyXLXvE5ErKhp_JIDs21kVqNzTGJYZ-n0uWzqaE3zdWB5n3MdnbAyKRj0A9eoobAn11GkCcqYpPje5ddSkJH_eip2H7DyFs9QrGOSujiWkQIPVkCUtpZL1z_o9=w120-h120-s-no?authuser=0',
    price: "7,90",
  },
  {
    id: 11,
    tags: ['especial', 'alcoólico', 'gelado'],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaXCq4i_M8MNtUjR2h-DCYlvplO7O_rse8gtoSHKnFc3L_X6ndXYDYcDeUGiJPZW1wvX9Bw5Y5B-hu7yXDLe9WzxbZXy6TLf8M5et_JaoBlg4umfUFWMbfFvFVQB0il2WgmoNeP3R2NVazIT7uawJxQI=w120-h120-s-no?authuser=0',
    price: "19,90",
  },
  {
    id: 12,
    tags: ['especial'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaWvHbR1dRsQnDWfrvkpwK5pT9VLr0j1gPB607qo7Pz9mCPFOD31R70hYmerJXTbywI3ovDtQ3nguRYRi5t9eWU58ugB0qC5NkS51L2akzKESFvslkDW365gnuBYJ4bYpcfOR4g8pxFLja1g9g1ozGbm=w120-h120-s-no?authuser=0',
    price: "19,90",
  },
  {
    id: 13,
    tags: ['especial'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaXU1m6R_R8MDTye_EW-2Lrd7dI1r2OTIPTSYkA5AJQdRIMQM4c4BjwpZzUXRe_n4R8lVZqziztVQ4LXBzgto3Dex96nW0203XiCsSSn0EiEal1C6AULP9K2DWnQvpsR3zmovYZS8FFj4k4afkUaBONC=w120-h120-s-no?authuser=0',
    price: "35,00",
  },
  {
    id: 14,
    tags: ['especial', 'alcoólico'],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    img: 'https://lh3.googleusercontent.com/pw/AJFCJaVBYXwJkq_woKG9XaDi_wYBht4iGTuDqJCIto1HyO1FbolNarC7BJIgUkU16woqh7ByT4ptH2I3CAUH6ppDgOBVPkjkRZNcV2TKFp0DRzbb3apaxA-qXLXdKDAJBvfjr0S22MNxgdqnEqq-4S3V2FgD=w120-h120-s-no?authuser=0',
    price: "25,00",
  },
]